### ISSUE TITLE
HSAIL source buffer not available

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/hcc#102]
Hi - I am trying to contribute a stream benchmark using HCC as aluded to #101 . the code does compile alright with the default `hcc-config --cxxflags` and `hcc-config --ldflags`, when I want to launch the benchmark however, I receive a SIGABRT from libc.so: clone() ! Inside rocm-gdb, I see the following:

```
ROCm-gdb: GPU Debugging has been successfully initialized]
GPU-STREAM
Version: 2.0
Implementation: HCC
Running kernels 100 times
Precision: double
Array size: 268.4 MB (=0.3 GB)
Total size: 805.3 MB (=0.8 GB)
Using HCC device AMD HSA Agent Fiji2
[New Thread 0x7fffb1e54700 (LWP 21503)]
[ROCm-gdb]: The code object for the current dispatch does not contain debug information
HSAIL source buffer not available
HSAIL kernel source debugging will not occur

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff5aeb700 (LWP 21501)]
0x00007ffff6ed2cc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(ROCm-gdb) bt
#0  0x00007ffff6ed2cc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6ed60d8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff669925b in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#3  0x00007ffff669c855 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#4  0x00007ffff6684547 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#5  0x00007ffff747f182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff6f9647d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
am I compiling against the wrong backend? I am confused. Can you help?

**Comment by david-salinas** [comment]
Is this still an issue with latest ROCm 1.9?
