### ISSUE TITLE
Error HSA_STATUS_ERROR_INVALID_ISA_NAME

### ISSUE THREAD

**Issue by vrajeshlm** [RadeonOpenCompute/hcc#272]
I am trying a simple code on following configuration:
- Hardware Info :   AMD APU A10-7860K   (No Discrete GPU)
- SW Info:              Ubuntu 16.04 64bit

Code I am Executing:
```
int main(int argc, char* argv[]) {
 std::vector<hc::accelerator> accs = hc::accelerator::get_all();
  assert(accs.size() && "Number of Accelerators == 0!");
}

```

I have compiled it with flag **-amdgpu-target=gfx700** 
while executing it gives me error HSA_STATUS_ERROR_INVALID_ISA_NAME.

Callstack:
```
### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INVALID_ISA_NAME (0x1017) at file:/home/vishwas/vrajesh_temp/PIM_14.04/hcc_git/hcc/lib/hsa/mcwamp_hsa.cpp line:2319

Thread 1 "hcfft_1D_R2C" received signal SIGABRT, Aborted.
0x00007ffff6d81428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(ROCm-gdb) backtrace
#0  0x00007ffff6d81428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6d8302a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6a94875 in Kalmar::HSADevice::IsCompatibleKernel(void*, void*) () from /opt/rocm/hcc-1.0/lib/libmcwamp_hsa.so
#3  0x000000000040336b in Kalmar::CLAMP::DetermineAndGetProgram(Kalmar::KalmarQueue*, unsigned long*, void**) ()
#4  0x0000000000403690 in Kalmar::KalmarBootstrap::KalmarBootstrap() ()
#5  0x0000000000402629 in __hcc_shared_library_init ()
#6  0x000000000040679d in __libc_csu_init ()
#7  0x00007ffff6d6c7bf in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x0000000000404399 in _start ()

```

**Comment by whchung** [comment]
@vrajeshlm I'm sorry to inform you that we don't actively support Kaveri chips now. So your program is likely not going to run, even though the compiler produces ISA for it. Please refer to https://github.com/RadeonOpenCompute/ROCm#supported-cpus for recommended system configuration for ROCm development.

**Comment by vrajeshlm** [comment]
@whchung  As per the reference provided by you...

```
**Not Supported or Very Limited Support Under ROCm**
- We do not support ROCm with PCIe Gen 2 enabled CPUs such as the AMD Opteron, Phenom, Phenom II, Athlon, Athlon X2, Athlon II and Older Intel Xeon and Intel Core Architecture and Pentium CPUs.
- We also do not support AMD Carrizo and Kaveri APU as host for compliant dGPU attachments.
```

It clearly says that support is not there for Kaveri APU for dGPU attachments, but we dont have any dGPU in our hardware setup. That means Kaveri APU is supported with internal graphics setup.

**Comment by whchung** [comment]
@vrajeshlm sorry I should be more specific. I was actually referring to this paragraph for supported CPUs:
```
Current CPUs which support PCIe Gen3 + PCIe Atomics are:
Intel Xeon E5 v3 or newer CPUs;
Intel Xeon E3 v3 or newer CPUs;
Intel Core i7 v3, Core i5 v3, Core i3 v3 or newer CPUs (i.e. Haswell family or newer).
```
